- import_tasks: selinux_config.yml

- name: insert pm.state in php-fpm www.conf
  lineinfile:
    path: "{{ php_fpm_d_www_conf }}"
    backup: yes
    line: pm.status_path = "/{{ php_fpm_status }}"
    regexp: '^pm.status_path.*'
    state: present
  notify:
    - reload php-fpm service
  
- name: copy php-fpm user parameter for zabbix agent
  template: src=userparameter_php_fpm.conf dest={{ zabbix_agent_d_dir }}
  notify:
   - restart zabbix-agent service

- name: copy php-fpm config for nginx
  template: src=php_fpm_status.conf dest={{ nginx_conf_d_dir }}
  notify:
   - reload nginx service
   - curl php-fpm status


