- name: install nginx vi yum
  hosts: nginx_linux
  remote_user: test.admin
  become: yes
  become_method: sudo
  become_user: root
  pre_tasks:
    - import_tasks: pre_tasks/semanage.yml
    - import_tasks: pre_tasks/epel/epel.yml
  roles:
    - { role: nginx_yum_install }
  vars:
    nginx_vhosts:
      - server_name: "site1.example.com"
        listen: "80 default_server"
        root: "{{ nginx_www_path }}/site1.example.com"
        index: "index.php index.html index.htm"
        template: "conf.d/php_host.conf"
        php:
      - server_name: "127.0.0.1"
        index: "index.html index.htm"
        template: "nginx_status.conf"

