- name: check if exists zabbix.repo
  shell: ls /etc/yum.repos.d/zabbix.repo
  register: result
  ignore_errors: True
- name: copy zabbix.repo 
  copy: src=zabbix.repo dest=/etc/yum.repos.d/ mode=0644 owner=root group=root
  when: result|failed
- name: copy epel.repo
  copy: src=epel.repo dest=/etc/yum.repos.d/ mode=0644 owner=root group=root
- name: Rebuild the yum cache
  shell: yum clean all && yum makecache
  when: result|failed
