---
- name: copy epel repo
  template: src=epel.repo dest=/etc/yum.repos.d owner=root group=root mode=0644

- name: yum install {{ app_name }}
  yum: name={{ app_name }} state={{ app_state | default('installed') }} update_cache=yes
  notify: restart {{ app_name }} service


